language: java
install: true

addons:
  sonarcloud:
    organization: gustavomcarmo-github

jdk:
- oraclejdk8

before_install:
- openssl aes-256-cbc -K $encrypted_51ce51fc7d9b_key -iv $encrypted_51ce51fc7d9b_iv -in codesigning.asc.enc -out codesigning.asc -d

script:
- mvn clean install sonar:sonar -Dgoogle.geocode.api.key=$GOOGLE_GEOCODE_API_KEY -f google-geocode

cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"

after_success:
- cp .travis.settings.xml $HOME/.m2/settings.xml && mvn source:jar javadoc:jar gpg:sign deploy -DskipTests=true -f google-geocode
