name: Java CI/CD with Maven

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 21.0.2
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: 21.0.2
          cache: 'maven'
          cache-dependency-path: 'google-geocode/pom.xml'
          server-username: gustavomcarmo
      - name: Build with Maven
        run: mvn verify sonar:sonar -Dsonar.token=${{ secrets.SONAR_TOKEN }} -Dgoogle.geocode.api.key=${{ secrets.GOOGLE_GEOCODE_API_KEY }} -f google-geocode
